/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.util.Date;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

/**
 *
 * @author raul
 */
public class Commonspest extends javax.swing.JDialog {

    String versao, dataChave, dataEnvio, nomeEmpresa, email, fone, cnpj, endereco, bairro, cidade, caixa, cpuSerialA, cpuSerialB, hostAddress, hostName, macAddress, virtualAdapter, hDSerial;

    /**
     * Creates new form Ahnes
     */
    public Commonspest(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        //---------------------
        jSpinner1.setValue(50);
        
        jEditorPane1.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        panelDados = new javax.swing.JPanel();
        labelEmpresa = new javax.swing.JLabel();
        ftfnomeEmpresa = new javax.swing.JFormattedTextField();
        labelCnpj = new javax.swing.JLabel();
        ftfcnpj = new javax.swing.JFormattedTextField();
        labelEmail = new javax.swing.JLabel();
        ftfemail = new javax.swing.JFormattedTextField();
        labelFone = new javax.swing.JLabel();
        ftffone = new javax.swing.JFormattedTextField();
        labelEndereco = new javax.swing.JLabel();
        ftfendereco = new javax.swing.JFormattedTextField();
        labelBairro = new javax.swing.JLabel();
        ftfbairro = new javax.swing.JFormattedTextField();
        labelCidade = new javax.swing.JLabel();
        ftfcidade = new javax.swing.JFormattedTextField();
        labelNumDias = new javax.swing.JLabel();
        ftfNumeroDias = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        panelRodape = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        botaoCopiarIdMaquina = new javax.swing.JButton();
        botaoGerarChave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerar Chave de Ativação");

        panelDados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Terminal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 12))); // NOI18N

        labelEmpresa.setText("Empresa:");

        ftfnomeEmpresa.setText(" ");
        ftfnomeEmpresa.setMinimumSize(new java.awt.Dimension(280, 30));
        ftfnomeEmpresa.setPreferredSize(new java.awt.Dimension(280, 30));

        labelCnpj.setText("CNPJ:");

        ftfcnpj.setText(" ");
        ftfcnpj.setMinimumSize(new java.awt.Dimension(140, 30));
        ftfcnpj.setPreferredSize(new java.awt.Dimension(140, 30));
        ftfcnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfcnpjActionPerformed(evt);
            }
        });

        labelEmail.setText("E-Mail:");

        ftfemail.setText(" ");
        ftfemail.setMinimumSize(new java.awt.Dimension(280, 30));
        ftfemail.setPreferredSize(new java.awt.Dimension(280, 30));
        ftfemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfemailActionPerformed(evt);
            }
        });

        labelFone.setText("Fone:");

        ftffone.setText(" ");
        ftffone.setMinimumSize(new java.awt.Dimension(140, 30));
        ftffone.setPreferredSize(new java.awt.Dimension(140, 30));

        labelEndereco.setText("Endereço:");

        ftfendereco.setText(" ");
        ftfendereco.setMinimumSize(new java.awt.Dimension(280, 30));
        ftfendereco.setPreferredSize(new java.awt.Dimension(280, 30));
        ftfendereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfenderecoActionPerformed(evt);
            }
        });

        labelBairro.setText("Bairro:");

        ftfbairro.setText(" ");
        ftfbairro.setMinimumSize(new java.awt.Dimension(140, 30));
        ftfbairro.setPreferredSize(new java.awt.Dimension(140, 30));

        labelCidade.setText("Cidade:");

        ftfcidade.setText(" ");
        ftfcidade.setMinimumSize(new java.awt.Dimension(280, 30));
        ftfcidade.setPreferredSize(new java.awt.Dimension(280, 30));
        ftfcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfcidadeActionPerformed(evt);
            }
        });

        labelNumDias.setText("Nº Dias:");

        ftfNumeroDias.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ftfNumeroDias.setText("30");
        ftfNumeroDias.setMinimumSize(new java.awt.Dimension(280, 30));
        ftfNumeroDias.setPreferredSize(new java.awt.Dimension(280, 30));

        jLabel1.setText("Nº Acesso:");

        jSpinner1.setMinimumSize(new java.awt.Dimension(29, 30));
        jSpinner1.setPreferredSize(new java.awt.Dimension(29, 30));

        javax.swing.GroupLayout panelDadosLayout = new javax.swing.GroupLayout(panelDados);
        panelDados.setLayout(panelDadosLayout);
        panelDadosLayout.setHorizontalGroup(
            panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDadosLayout.createSequentialGroup()
                        .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEmpresa)
                            .addComponent(labelEmail))
                        .addGap(14, 14, 14)
                        .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftfemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ftfnomeEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelDadosLayout.createSequentialGroup()
                        .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEndereco)
                            .addComponent(labelCidade)
                            .addComponent(labelNumDias))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftfcidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ftfendereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ftfNumeroDias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDadosLayout.createSequentialGroup()
                        .addComponent(labelBairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ftfbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDadosLayout.createSequentialGroup()
                        .addComponent(labelCnpj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ftfcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDadosLayout.createSequentialGroup()
                        .addComponent(labelFone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ftffone, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDadosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDadosLayout.setVerticalGroup(
            panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmpresa)
                    .addComponent(ftfnomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCnpj)
                    .addComponent(ftfcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail)
                    .addComponent(ftfemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFone)
                    .addComponent(ftffone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEndereco)
                    .addComponent(ftfendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBairro)
                    .addComponent(ftfbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCidade)
                    .addComponent(ftfcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftfNumeroDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumDias)
                    .addComponent(jLabel1)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1))
        );

        panelRodape.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Identificação da Máquina", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 12))); // NOI18N
        jScrollPane1.setMinimumSize(new java.awt.Dimension(575, 150));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(575, 150));

        jEditorPane1.setText("<cole o parametro aqui>");
        jScrollPane1.setViewportView(jEditorPane1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        panelRodape.add(jScrollPane1, gridBagConstraints);

        botaoCopiarIdMaquina.setText("Copiar Identificação Máquina");
        botaoCopiarIdMaquina.setMaximumSize(new java.awt.Dimension(285, 23));
        botaoCopiarIdMaquina.setMinimumSize(new java.awt.Dimension(285, 23));
        botaoCopiarIdMaquina.setPreferredSize(new java.awt.Dimension(285, 23));
        botaoCopiarIdMaquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCopiarIdMaquinaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        panelRodape.add(botaoCopiarIdMaquina, gridBagConstraints);

        botaoGerarChave.setText("Gerar Chave Ativação");
        botaoGerarChave.setEnabled(false);
        botaoGerarChave.setMinimumSize(new java.awt.Dimension(285, 23));
        botaoGerarChave.setPreferredSize(new java.awt.Dimension(285, 23));
        botaoGerarChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGerarChaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        panelRodape.add(botaoGerarChave, gridBagConstraints);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRodape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRodape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoGerarChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGerarChaveActionPerformed
        gerarChaveAtivacao();
    }//GEN-LAST:event_botaoGerarChaveActionPerformed

    private void botaoCopiarIdMaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCopiarIdMaquinaActionPerformed
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        lerIdMaquina();
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botaoCopiarIdMaquinaActionPerformed

    private void ftfenderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfenderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfenderecoActionPerformed

    private void ftfemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfemailActionPerformed

    private void ftfcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfcidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfcidadeActionPerformed

    private void ftfcnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfcnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfcnpjActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Commonspest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Commonspest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Commonspest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Commonspest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Commonspest dialog = new Commonspest(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCopiarIdMaquina;
    private javax.swing.JButton botaoGerarChave;
    private javax.swing.JFormattedTextField ftfNumeroDias;
    private javax.swing.JFormattedTextField ftfbairro;
    private javax.swing.JFormattedTextField ftfcidade;
    private javax.swing.JFormattedTextField ftfcnpj;
    private javax.swing.JFormattedTextField ftfemail;
    private javax.swing.JFormattedTextField ftfendereco;
    private javax.swing.JFormattedTextField ftffone;
    private javax.swing.JFormattedTextField ftfnomeEmpresa;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel labelBairro;
    private javax.swing.JLabel labelCidade;
    private javax.swing.JLabel labelCnpj;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEmpresa;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelFone;
    private javax.swing.JLabel labelNumDias;
    private javax.swing.JPanel panelDados;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelRodape;
    // End of variables declaration//GEN-END:variables

    //-------------------------
    public void lerIdMaquina() {

        if (jEditorPane1.getText() == null || jEditorPane1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o registro do terminal.");
            jEditorPane1.requestFocus();
            return;
        }

        String str = OS.Descriptografar(jEditorPane1.getText());
        StringTokenizer st2 = new StringTokenizer(str, "|");

        //-----------------------------------------------
        //sistema
        versao = st2.nextToken();
        dataChave = st2.nextToken();
        dataEnvio = st2.nextToken();

        //empresa
        nomeEmpresa = st2.nextToken();
        cnpj = st2.nextToken();
        email = st2.nextToken();
        fone = st2.nextToken();
        endereco = st2.nextToken();
        bairro = st2.nextToken();
        cidade = st2.nextToken();

        //maquina
        caixa = st2.nextToken();

        //Serial da CPU
        cpuSerialA = st2.nextToken();
        //Serial da CPU
        cpuSerialB = st2.nextToken();
        //HostAddress
        hostAddress = st2.nextToken();
        //HostName
        hostName = st2.nextToken();
        //MacAddress
        macAddress = st2.nextToken();
        //VirtualAdapter
        virtualAdapter = st2.nextToken();
        //Serial do HD:
        hDSerial = st2.nextToken();

        //mostrar na tela --------------------------------------------------------------------
        ftfbairro.setText(bairro);
        ftfcidade.setText(cidade);
        ftfcnpj.setText(cnpj);
        ftfemail.setText(email);
        ftfendereco.setText(endereco);
        ftffone.setText(fone);
        ftfnomeEmpresa.setText(nomeEmpresa);

        jEditorPane1.setText(
                " Data Chave: " + new Date(Long.valueOf(dataChave))
                + "\n Data Envio: " + dataEnvio
                + "\n a) Serial da CPU: " + cpuSerialA
                + "\n b) Serial da CPU: " + cpuSerialB
                + "\n HostAddress: " + hostAddress
                + "\n HostName: " + hostName
                + "\n MacAddress: " + macAddress
                + "\n VirtualAdapter: " + virtualAdapter
                + "\n Serial do HD: " + hDSerial
        );

        //-------------------------------------------------
        botaoGerarChave.setEnabled(true);
        botaoCopiarIdMaquina.setEnabled(false);
    }

    private void gerarChaveAtivacao() {

        String chave, numeroDias, numeroAcesso;

        if (jEditorPane1.getText() == null || jEditorPane1.getText().isEmpty()) {
            jEditorPane1.requestFocus();
            return;
        }

        //VALIDAR CAMPOS
        if (ftfnomeEmpresa.getText() == null || ftfnomeEmpresa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo de preenchimento obrigatorio");
            ftfnomeEmpresa.requestFocus();
            return;
        }

        if (ftfcnpj.getText() == null || ftfcnpj.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo de preenchimento obrigatorio");
            ftfcnpj.requestFocus();
            return;
        }
        if (ftfemail.getText() == null || ftfemail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo de preenchimento obrigatorio");
            ftfemail.requestFocus();
            return;
        }
        if (ftffone.getText() == null || ftffone.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo de preenchimento obrigatorio");
            ftffone.requestFocus();
            return;
        }
        if (ftfendereco.getText() == null || ftfendereco.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo de preenchimento obrigatorio");
            ftfendereco.requestFocus();
            return;
        }
        if (ftfbairro.getText() == null || ftfbairro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo de preenchimento obrigatorio");
            ftfbairro.requestFocus();
            return;
        }
        if (ftfcidade.getText() == null || ftfcidade.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo de preenchimento obrigatorio");
            ftfcidade.requestFocus();
            return;
        }

        //----------------------------------------------------------------------
        //sistema
        versao = "|" + "1.01";
        dataChave = "|" + String.valueOf(System.currentTimeMillis());
        dataEnvio = "|" + String.valueOf(System.currentTimeMillis());

        //empresa
        nomeEmpresa = "|" + ftfnomeEmpresa.getText();
        cnpj = "|" + ftfcnpj.getText();
        email = "|" + ftfemail.getText();
        fone = "|" + ftffone.getText();
        endereco = "|" + ftfendereco.getText();
        bairro = "|" + ftfbairro.getText();
        cidade = "|" + ftfcidade.getText();

        //maquina
        caixa = "|" + "C1";

        //Serial da CPU
        cpuSerialA = "|" + cpuSerialA;
        //Serial da CPU
        cpuSerialB = "|" + cpuSerialB;
        //HostAddress
        hostAddress = "|" + hostAddress;
        //HostName
        hostName = "|" + hostName;
        //MacAddress
        macAddress = "|" + macAddress;
        //VirtualAdapter
        virtualAdapter = "|" + virtualAdapter;
        //Serial do HD:
        hDSerial = "|" + hDSerial;

        //dias de ativacao
        numeroDias = "|" + ftfNumeroDias.getText();

        numeroAcesso = "|" + jSpinner1.getValue().toString();

        //--------------------------------------------
        chave = versao + dataChave + dataEnvio + nomeEmpresa + cnpj + email + fone + endereco + bairro + cidade + caixa + cpuSerialA + cpuSerialB + hostAddress + hostName + macAddress + virtualAdapter + hDSerial + numeroDias + numeroAcesso;

        jEditorPane1.setText(OS.Encriptar(chave));

        JOptionPane.showMessageDialog(null,
                "Próximo passo:"
                + "\n"
                + "\n Agora envie por e-mail o código gerado ao CLIENTE."
                + "\n", "Aviso do Sistema", JOptionPane.INFORMATION_MESSAGE);
    }

}
